### ISSUE TITLE
something wired when using fmt.Sprintf in go

### ISSUE THREAD

**Issue by rleungx** [sourcegraph/browser-extensions#139]
I have found something wired recently. When I was reviewing some PRs which contain something like `fmt.Sprintf("%5d", ...)` written in go and moved my mouse pointer on it, it will turn to `fmt.Sprintf("]", ...)` occasionally.  And this happened not only in our repo. 
After I turned it off, it became normal.

Here is the version of Sourcegraph I was using. 
```
Version
1.12.2
```

**Comment by ijsnow** [comment]
Thanks for reporting! This is a bug in [codeintellify's](https://github.com/sourcegraph/codeintellify) `convertNode` function. Filed in that repository https://github.com/sourcegraph/codeintellify/issues/54.
