### ISSUE TITLE
not active when viewing specific commits on github?

### ISSUE THREAD

**Issue by jaffee** [sourcegraph/browser-extensions#143]
I'm using Chrome on OSX.

For example on this page: https://github.com/pilosa/pilosa/commit/19af6ad623937ad00b31a5b4783e3c45fce46db4 the extension does not appear to be active. The only indication I have is a greyed out "Configure Sourcegraph" at the top: 
![screen shot 2018-09-07 at 11 05 44 am](https://user-images.githubusercontent.com/926067/45230310-160f4600-b28e-11e8-9b4d-b9eca84e58cf.png)

Is this expected behavior?

P.S. loving the extension otherwise - great work!

**Comment by nicksnyder** [comment]
@ijsnow I see an error in the JS console

![image](https://user-images.githubusercontent.com/754768/45230730-ae053380-b27e-11e8-90fc-3b31950c8ba5.png)

**Comment by ijsnow** [comment]
Hi @jaffee I'm glad you like the extension!

I see the same error as @nicksnyder which tells me that sourcegraph.com doesn't have that commit. To confirm this, I tried to find the commit in the sourcegraph UI and it definitely doesn't have it: https://sourcegraph.com/github.com/pilosa/pilosa/-/commit/19af6ad623937ad00b31a5b4783e3c45fce46db4. 

Going further, I checked the commits page on GitHub and don't see the commit in there anymore. Is it possible that there was a force push removing that commit? How did you get to that page in the GitHub UI?

For code intelligence to work we need the revision to be in the actual repository. The question now is where is the commit?

**Comment by jaffee** [comment]
oh... this is rather interesting. That commit was linked to from this comment on the pull request https://github.com/pilosa/pilosa/pull/1628#issuecomment-419315318 which you'll notice no longer links to the same commit.

I clicked on the commit link in the email I got from github about that comment which looked like this:
![screen shot 2018-09-07 at 11 52 59 am](https://user-images.githubusercontent.com/926067/45232353-bcf6e080-b294-11e8-9a36-edf5b49a9254.png)

I just talked to @travisturner and he confirmed that he did a force push and then manually updated that commit link.

Weird situation - sorry for the trouble! I'll close this.

**Comment by ijsnow** [comment]
Don't be sorry! It was no trouble at all. Sorry you experienced this issue and that you lost time trying to figure it out. I've opened an issue for investing time into coming up with a better UX when errors are encountered https://github.com/sourcegraph/browser-extensions/issues/144.
