### ISSUE TITLE
Update to Babel 7

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/browser-extensions#154]
This brings a bunch of improvements, but most importantly in the webapp it made async/await "just work". Promises have a lot of caveats that frequently come up in code review so this would be great to remedy. We already did this in the web app, so this should be trivial to apply here. See https://github.com/sourcegraph/sourcegraph/pull/13006

**Comment by sqs** [comment]
done in 4f84e33b8c278ca829b4e5564fe59b2f50f723e8
