### ISSUE TITLE
LoadingSpinner error at build time

### ISSUE THREAD

**Issue by sqs** [sourcegraph/browser-extensions#167]
Locally and in CI I see this error, whch does not seem to be actually causing any problems:

```
Error: Could not import `../node_modules/@sourcegraph/react-loading-spinner/lib/LoadingSpinner.css` from any of the following locations:
  /home/travis/build/sourcegraph/browser-extensions/node_modules/@sourcegraph/codeintellify/node_modules/@sourcegraph/react-loading-spinner/lib/LoadingSpinner.css
  /home/travis/build/sourcegraph/node_modules/@sourcegraph/react-loading-spinner/lib/LoadingSpinner.css
  /node_modules/@sourcegraph/react-loading-spinner/lib/LoadingSpinner.css
  /home/travis/build/sourcegraph/browser-extensions/src/node_modules/@sourcegraph/react-loading-spinner/lib/LoadingSpinner.css
```

Example: https://travis-ci.org/sourcegraph/browser-extensions/jobs/428351223

**Comment by chrismwendt** [comment]
https://github.com/sourcegraph/codeintellify/blob/849914f66156cc1506a9b3a15afd7646275103fe/src/HoverOverlay.scss#L1 looks suspicious (why `../node_modules` instead of the bare package name?)

**Comment by felixfbecker** [comment]
Yeah it should use a bare package name

**Comment by ijsnow** [comment]
I tried using the bare package name and it didn't work. I think theres a problem with the loading spinner package.
