### ISSUE TITLE
Revisit not installing binary on each build

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/browser-extensions#193]
I had to [remove the env vars telling cypress to not install the binary](https://github.com/sourcegraph/browser-extensions/commit/afeb19f49de9e0b2f5f0eb52e15d3b9f7c36d56b) and [force install the binary](https://github.com/sourcegraph/browser-extensions/commit/3c0cebb4819325f765f37442e8b4831916c324a0) because the build was failing on the release branch every time saying that the binary wasn't installed. For whatever reason the binary was there for PR builds but not the release builds.

I assume you had that skip for build speed reasons. We may want to try to fix this or just leave it. This could either be because of caching differences between yarn and npm or just that the cache holding the binary expired.

**Comment by felixfbecker** [comment]
Did you figure this out?
