### ISSUE TITLE
How to hide these popups 

### ISSUE THREAD

**Issue by yashwanth2804** [sourcegraph/browser-extensions#232]
![screenshot from 2018-10-05 09-47-01](https://user-images.githubusercontent.com/8038593/46515879-1813f700-c884-11e8-9fe1-fb40e654bc7c.png)

**Comment by sqs** [comment]
You can disable code intelligence for shell files for your user account by signing into Sourcegraph.com (if you aren't already), going to Extensions (in top nav), and disabling the **Bash** extension. Once/if you confirm this solves your problem, I will rename this issue to be about improving docs for this case.

(If you want to disable hovers on ALL files, or make it so they only appear when you hold down alt/option, please +1 https://github.com/sourcegraph/browser-extensions/issues/224.)

**Comment by joebowbeer** [comment]
BTW, I don't always see Extensions menu at Sourcegraph.com. On OSX, I only see it in Safari, but **not** in Chrome (69.0.3497.100) or Firefox. On iPad, I see it in Safari and Chrome (69.0.3497.105).

**Comment by chrismwendt** [comment]
@joebowbeer Can you post a screenshot of the Extensions menu you're referring to? Is it the one in the browser extension options page?

![image](https://user-images.githubusercontent.com/1387653/46554294-abedbf00-c894-11e8-9a95-bd55d1cd3abc.png)

**Comment by joebowbeer** [comment]
@chrismwendt I'm referring to the Extensions item at the top.

![6c0d3e73-5f46-4a70-8426-22bf52afdf5f](https://user-images.githubusercontent.com/28679/46554539-7f867280-c895-11e8-98c8-1ac12ff62fea.jpeg)

**Comment by chrismwendt** [comment]
@joebowbeer I see, that's actually unrelated to browser extensions, but we can help out more if you file it on https://github.com/sourcegraph/sourcegraph/issues/new

**Comment by sqs** [comment]
Closing because I have not been able to repro the reported issue, and we've made many fixes to this general area since this issue was filed. @yashwanth2804, please let me know if you are still experiencing this issue.
