### ISSUE TITLE
Add shadow to hover tooltip

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/browser-extensions#255]
@ijsnow We talked about adding a shadow to the hover tooltip on code hosts. 

Creating an issue for tracking this change.

**Comment by ijsnow** [comment]
Should this be added to the tooltip on all code hosts?

**Comment by francisschmaltz** [comment]
Yeah I think we discussed that. Add it to add code hosts. Do you still have the value for the shadow?

**Comment by ijsnow** [comment]
Before you had said to just do GitLab but seems like people would like it elsewhere(from the issue in sourcegraph/sourcegraph).

`box-shadow: rgba(0,0,0,0.05) 0 0 16px 1px`
